sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alexvalle92/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexvalle92/docker-react npm run test
